### ISSUE TITLE
delfi run problem conflicting local python setup

### ISSUE THREAD

**Issue by roveri-marco** [AI-Planning/planutils#46]
While running delfi I bumed in this problem:

```
shell > delfi Examples/blocks-domain-complete.pddl Examples/blocks-problem1.pddl
Traceback (most recent call last):
  File "/workspace/delfi/plan-ipc.py", line 13, in <module>
    from dl_model import selector
  File "/workspace/delfi/dl_model/selector.py", line 4, in <module>
    from keras.models import model_from_json
  File "/usr/local/lib/python2.7/dist-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/__init__.py", line 2, in <module>
    from . import np_utils
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/np_utils.py", line 6, in <module>
    import numpy as np
  File "/home/marco/.local/lib/python3.8/site-packages/numpy/__init__.py", line 132
    raise ImportError(msg) from e
```

It seems that it tries to use my local version of  numpy instead of using the one in the local internal to the singularity/docker image. TO have it running I had to unset the PYTHONPATH environment variable. May be one can specify to then run in a fresh environment by passing -e flag to the run singularity command i.e.  `singularity run -e  $(dirname $0)/delfi.sif $@`

**Comment by ctpelok77** [comment]
So the issue is not with Delfi, but with how a singularity image is called, correct?
Is that the same for all other packages?

**Comment by roveri-marco** [comment]
> So the issue is not with Delfi, but with how a singularity image is called, correct? Is that the same for all other packages?

yes fom what I see yes. Indeed, unsetting my PYTHONHOME env var the planner works. Indeed, singularity inherits some (not clear which one) of the env variables of the host shell.

**Comment by FlorianPommerening** [comment]
> Very weird that it would import things outside of the image...any ideas of what's going on @FlorianPommerening ?

Well, I think it's what @roveri-marco said: the singularity process uses PYTHONPATH or PYTHONHOME from the host system. The singularity call is not sandboxed (I think this is intentional so that the planner can access the input files without us having to mount the directory with the PDDL files explicitly). This means that the directories mentioned in the PYTHONPATH actually are accessible and can be used. I don't know why singularity would use the host value of PYTHONPATH, that seems stupid.

Here is the documentation of how things work in Singularity 3.6/3.7 but there is a note at the top saying that behavior changed from 3.5 to 3.6 so this might depend on the singularity version. https://sylabs.io/guides/3.7/user-guide/environment_and_metadata.html#environment-from-the-host
It looks like most variables from the host are copied and you can prevent that with `-e` (`--cleanenv` is mentioned in the documentation, this is just an alias). This also is the recommended solution for issues caused by PYTHONPATH. So maybe adding this to the call of all planners would be helpful. I don't see a downside in this, as I don't see why they would depend on host environment variables.

**Comment by haz** [comment]
Wild.

Completely agree -- singularity calls should be `-e`'d by default.

@roveri-marco : Any chance you could make the small modification across the board as part of your PR? I.e., just add the `-e` option to the singularity run calls. To my knowledge, there isn't a single one that is assuming local environment variables.

**Comment by roveri-marco** [comment]
@haz Sure I can add it the the optic PR.
